
// Objective-C API for talking to the following Go packages
//
//	ReverseBinding
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Test_FRAMEWORK_H__
#define __Test_FRAMEWORK_H__

#include "Test.objc.h"
#include "universe.objc.h"

#endif
