// Objective-C API for talking to ReverseBinding Go package.
//   gobind -lang=objc ReverseBinding
//
// File is generated by gobind. Do not edit.

#ifndef __Test_H__
#define __Test_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* TestShowDate(NSDate * date);

#endif
